spring:
  application:
    name: bank
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bank?options=-c%20timezone=Europe/Kyiv}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    user:
      name: user
      password: password

server:
  port: 8080
  error:
    include-message: always
